### ISSUE TITLE
Required code missing from observation resource

### ISSUE THREAD

**Issue by ghoward9** [qe-collaborative-services/1115-hub#111]
We are seeing submissions from Healtheconnections failing the validator because some observation resources are missing the required code field where a LOINCCode is expected.
![IG](https://github.com/qe-collaborative-services/1115-hub/assets/158187027/901cdf18-a085-42d8-81cb-5a9615477353)

@raphaelvp @reeager @shah

**Comment by reeager** [comment]
I will communicate this to Bernard and David.

**Comment by drubacha** [comment]
Looking at testcase11.csv file  line 21, LOINC is missing for Question Code, Question System is blank,  LOINC Is missing for Answer Code and Answer Code System is blank.  Line 28 also has the same missing LOINC codes.  My understanding is because these are missing they are not showing in the FHIR code.CodeableConcept.coding.code.  If this is not the issue happening above can you please point to the correct test case.
[SCREENING_healtheconnections-20240409-testcase11.csv](https://github.com/qe-collaborative-services/1115-hub/files/14933860/SCREENING_healtheconnections-20240409-testcase11.csv)

**Comment by drubacha** [comment]
It appears that the issue was with the column order of the enriched files being sent to QCS that was causing the FHIR objects to not populate correctly. this has now been resolved.

**Comment by harmonf13** [comment]
Good news.  We'll watch for the next release and monitor the tests that come through and let you know if we don't see it resolved.
