### ISSUE TITLE
FullURL should be an absolute url

### ISSUE THREAD

**Issue by ghoward9** [qe-collaborative-services/1115-hub#165]
FullURL should be an absolute URL (even if it's not reachable)

Invalid Example:
CNYSCN-healtheconnections-20240419-testcase1-MRN

Valid Example:
http://10.80.80.125:9006/r4/Patient/CNYSCN-healtheconnections-20240419-testcase1-MRN

**Comment by shah** [comment]
@ghoward9 this file is created by the "Crossroads SCN" team and should be corrected in the source and then supplied to TechBD.

**Comment by ghoward9** [comment]
I am referring to CSV's sent to techBD and the FHIR that is generated from those CSV's

**Comment by shah** [comment]
@ratheesh-kr @alan-francis please fix this and report here about when the new release can go out for testing.

**Comment by alan-francis** [comment]
@ghoward9 : At present we are having `ids` as the `fullUrl` for each resource like you have mentioned above. We are currently not having any URLs coming through the CSVs as well. So if its okay, we can prepend the ids with a base URL like `https://fhir.api.techbd.org/` so that the `fullUrl` becomes `https://fhir.api.techbd.org/Patient/CNYSCN-healtheconnections-20240419-testcase1-MRN` and thus an absolute URL is being given.  If this is ok, we can update it in the next release.

@shah @ratheesh-kr @raphaelvp

**Comment by ghoward9** [comment]
Yes this fix should work.

**Comment by ratheesh-kr** [comment]
Updated in version v0.23.6
