### ISSUE TITLE
Updated CSV Omnibus Rules

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#178]
https://github.com/qe-collaborative-services/1115-hub/blob/5d570a082978349c9d43ffb689d47467b43044a0/Phase%201%20CSV/ahc-hrsn-2024-05-28-omnibus-rules.xlsx Please find newly updated Omnibus Rules

**Comment by ratheesh-kr** [comment]
@reeager  Updated in Version 0.30.0.

* Added new rule - Row 5 - Please do not reject because of case sensitivity.
* Demographics - Added PHONE, SSN.
* Demographics - Changed field SEXUAL_ORIENTATION_DESCRIPTION to SEXUAL_ORIENTATION_CODE_DESCRIPTION.
* Demographics - Changed PREFERRED_LANGUAGE_DESCRIPTION to PREFERRED_LANGUAGE_CODE_DESCRIPTION
* SCREENING_CODE_DESCRIPTION - Added new data "NYS AHC HRSN screening".
* SCREENING_CODE_SYSTEM_NAME - Added new data 'NYS standard'.

Two more items pending, need more clarification for those items
* SCREENING_CODE - 96777-8', '97023-6', defined code by NYS.
* Column H -Changed Calculated weekly Physical Activity Score to Calculated Physical Activity Score.

@shah @raphaelvp @alan-francis

**Comment by alan-francis** [comment]
@reeager : Can you clarify what should be the code that needs to be validated for the `SCREENING_CODE` which is `defined code by NYS` ? Also could you provide us with the updated synthetic test files?

@ratheesh-kr @raphaelvp @shah

**Comment by reeager** [comment]
NYS Waiver has only asked for 12 questions rather than the full screening. However there is no LOINC code for all core questions and 2 supplemental questions so need to have a local parent code. This is ultimately a placeholder.

**Comment by reeager** [comment]
[QE_ADMIN_DATA_2024-05-30.csv](https://github.com/qe-collaborative-services/1115-hub/files/15500666/QE_ADMIN_DATA_2024-05-30.csv)

**Comment by raphaelvp** [comment]
Resolved in v0.31.1
