### ISSUE TITLE
Hixny's tests sitting in ingress

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#185]
Hixny ran tests last week and tests are sitting in ingress and did not get to egress.

**Comment by alan-francis** [comment]
For zip file ingestion process we are expecting the zip file to be ingested as a .zip file of a single set or multiple 
sets of CSV triplets(DEMOGRAPHIC_DATA_*.csv, QE_ADMIN_DATA_*.csv & SCREENING_*.csv). 

From the screenshot, we can see that the zip provided has got another folder /tmp and inside that we are missing 
the file patterns mentioned above. Instead of DEMOGRAPHIC_DATA_*.csv, we are having 
UPDATED_Demo_Data_testcase_2.csv. Ideally, we are expecting a zip file of a set of 3 CSV files named like 
DEMOGRAPHIC_DATA_*.csv, QE_ADMIN_DATA_*.csv & SCREENING_*.csv.

![hixny_error1](https://github.com/qe-collaborative-services/1115-hub/assets/39818587/856244cc-7621-448f-98b7-94254e8e7088)
![hixny_error2](https://github.com/qe-collaborative-services/1115-hub/assets/39818587/226dc5fb-6a28-453c-90c1-0ebcd546aefa)

**Comment by raphaelvp** [comment]
Hixny made the changes and the tests were successful.
