### ISSUE TITLE
Testcases missing patient resource/duplicate FHIR

### ISSUE THREAD

**Issue by ratheesh-kr** [qe-collaborative-services/1115-hub#187]
In egress/7133944a-0760-4bcc-8044-2b6af1d1347f/diagnostics.md you will see:

`emitResources` STDERR

•	Conversion Error: Could not convert string '(350)928-2798x37039' to INT64
•	Conversion Error: Could not convert string '(350)928-2798x37039' to INT64
•	Conversion Error: Could not convert string '+1-724-921-0250x417' to INT64
•	Conversion Error: Could not convert string '+1-724-921-0250x417' to INT64
•	Conversion Error: Could not convert string '288.778.4689x839' to INT64
•	Conversion Error: Could not convert string '288.778.4689x839' to INT64
•	Conversion Error: Could not convert string '678-297-0259' to INT64
•	Conversion Error: Could not convert string '678-297-0259' to INT64
•	Conversion Error: Could not convert string '731-530-0331' to INT64
•	Conversion Error: Could not convert string '731-530-0331' to INT64
•	Conversion Error: Could not convert string '715.831.0100' to INT64
•	Conversion Error: Could not convert string '715.831.0100' to INT64

Then, take a look at these … 

1.	there are two FHIR JSONs for each test case – but the weird thing is that 
2.	the two files are not identical – one is bigger than the other

![image](https://github.com/qe-collaborative-services/1115-hub/assets/2518450/b055a366-3aab-4c03-acee-8d96da311696)

@alan-francis @raphaelvp

**Comment by alan-francis** [comment]
We are generating FHIR JSON per patient per encounter. So if a single test case contains multiple encounters, we will generate multiple JSON files with the respective resource data. The file names are also generated w.r.t the PAT_MRN_ID and ENCOUNTER_ID, ie, fhir-<PAT_MRN_ID>-<ENCOUNTER_ID>.json. 

The string cast error recorded above will be fixed in the latest release of 0.31.2.

@ratheesh-kr @raphaelvp @shah @reeager @ghoward9

**Comment by raphaelvp** [comment]
Resolved in v0.31.2
