### ISSUE TITLE
Update orchestration to integrate 1115-Hub FHIR API calls and results capture

### ISSUE THREAD

**Issue by raphaelvp** [qe-collaborative-services/1115-hub#56]
- [x] Add a new CLI argument to orchctl.ts called `--publish-fhir` which would use Deno’s `fetch` function to post the generated FHIR content to the FHIR endpoint and store the results into the egress folder as `fhir-result.json` or similar.
- [x] Update the cron job pass to pass in `--publish-fhir` to `orchctl.ts` during the cron job execution to automatically push to FHIR content to the FHIR endpoint after each egress session.
- [x] Use proper QE ID expected by FHIR endpoints

**Comment by mdvertola** [comment]
I noticed with last commit here we are now using this hard-coded API endpoint `https://40lafnwsw7.execute-api.us-east-1.amazonaws.com/`. Apologies if this is lost in emails/ communications somewhere else but I wanted to highlight it here just to centralize that. 

Im sure this was done to get an MVP for this feature shipped (which I totally understand) and this may be out of our teams control/ scope to change but if possible we should try to get this mapped to a domain rather than an aws execute endpoint in the case that this apigateway ever gets rebuilt. 

Additionally, we may want to discuss how this will play out when it comes to development/ production environments and probably set the goal of loading this in via env vars to support that.

**Comment by raphaelvp** [comment]
Resolved by #65
